
development:
  adapter: mysql2  # Rails 3.x uses the mysql2 adapter
  encoding: utf8
  database: fate_dashboard_development
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock


test:
  adapter: mysql2  # Rails 3.x uses the mysql2 adapter
  encoding: utf8
  database: fate_dashboard_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2  # Rails 3.x uses the mysql2 adapter
  encoding: utf8
  database: fate_dashboard_production
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock